In [51]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [52]:
a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [53]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [54]:
#転置行列
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [55]:
#行列演算ではない！
a*a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [56]:
#内積を求めるにはdot演算子を使う
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

In [57]:
#逆行列
np.linalg.inv(np.dot(a, a.T))

array([[ 1.42592593, -0.59259259],
       [-0.59259259,  0.25925926]])

In [58]:
np.dot(np.dot(a, a.T),np.linalg.inv(np.dot(a, a.T)))

array([[ 1.,  0.],
       [ 0.,  1.]])

# 便利かもしれない道具(numpy)

In [59]:
np.arange(0, 1, 0.3)

array([ 0. ,  0.3,  0.6,  0.9])

In [60]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [61]:
np.reshape(np.arange(6),(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
np.reshape(np.arange(6),(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [63]:
np.linspace(0,2,3)

array([ 0.,  1.,  2.])

In [64]:
np.linspace(0,2,4)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [65]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [66]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [67]:
np.random.seed(0)
np.random.random((2,3))

array([[ 0.5488135 ,  0.71518937,  0.60276338],
       [ 0.54488318,  0.4236548 ,  0.64589411]])

In [68]:
a = np.reshape(np.arange(12), (3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a[:,0]

array([0, 4, 8])

In [70]:
a[:,0:2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [71]:
a[:,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])